[package]
name = "pratt-gen-test"
version = "0.1.0"
edition = "2021"

[dependencies]
once_cell = "1.19.0"
pratt-gen = { version = "0.1.0", path = "../pratt-gen" }
stacker = "0.1.15"

[features]
trace = []
