[package]
name = "peggen-examples"
version = "0.2.1"
edition = "2021"

[dependencies]
bumpalo = { version = "3.16.0", features = ["boxed"] }
once_cell = "1.19.0"
peggen = { version = "0.2", path = "../peggen", features = ["trace"] }
stacker = "0.1.15"
